import { ColorsAlphaValuesConfig } from '../src/declarations/interfaces/colors-alpha-values-config.interface';
import { readFile, writeFile } from 'fs/promises';

async function writeContentToFile(fileData: string): Promise<void> {
  await writeFile('src/styles/maps/alpha-colors.map.scss', fileData, null);
}

async function getAlphaColorsMapScssFileContent(): Promise<string> {
  return await readFile('src/assets/configs/alpha-colors-config.json', { encoding: 'utf8' })
    .then((content: string) => JSON.parse(content))
    .then((alphaValues: ColorsAlphaValuesConfig.AlphaValue[]) => {
      const alphaColorsMapElements: string[] = alphaValues.map(
        (alphaValue: ColorsAlphaValuesConfig.AlphaValue) => `'${alphaValue.name}': ${alphaValue.value / 100}`
      );

      const emptyFileContent: string =
        '/** @file Automatically generated by create-alpha-colors-map.script.ts. Edit alpha-colors-config.json*/\n';
      const colorsMapElementsString: string = alphaColorsMapElements.join(',\n  ');
      return `${emptyFileContent}\n$alphaColorsMap: (\n  ${colorsMapElementsString},\n);\n`;
    });
}

Promise.resolve()
  .then(() => getAlphaColorsMapScssFileContent())
  .then((fileData: string) => writeContentToFile(fileData));
